# Generated by Django 5.1 on 2024-10-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=30)),
                ('contact', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('batch_no', models.CharField(max_length=40)),
                ('shelf_no', models.CharField(max_length=30)),
                ('expire_data', models.DateField()),
                ('mfg_data', models.DateField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
