# Generated by Django 5.1 on 2024-10-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='medicine',
        ),
    ]
